### PR TITLE
Fixing sql error on a recent mysql server #219 - Updated SQL Query

### PR DESCRIPTION
**Pull request by omazany**
This code fixes an error with MySQL strict mode. In the select query, the ba_id is chosen twice, so I believe the second ba_id expression is unnecessary, also ba_id and currency should be unique, so there shouldn't be a problem adding them to group by. Please let me know if you have a better solution or if you merge this request.

### CODE REVIEW

**Comment by omazany** [comment]
Hi Bjorn, this code seems to be working well with my data. No more DB Errors caused by ONLY_FULL_GROUP_MODE in recent MySQL servers

**Comment by bjendres** [comment]
Great stuff, @omazany, thanks! Are you sure the the statement
- still runs on the other msyql configurations
- yields the same results?

If so, I'll merge.

**Comment by omazany** [comment]
> 
> 
> Great stuff, @omazany, thanks! Are you sure the the statement
> 
>     * still runs on the other msyql configurations
> 
>     * yields the same results?
> 
> 
> If so, I'll merge.

Hi Bjorn,

if I am correct, there are only columns added in GROUP BY statement so this should work on other mysql configurations without a problem. 

It runs definitely on current cividev environment with MySQL option ONLY_FULL_GROUP_BY turned on nad fixes the DB error. However, I have no means to test different MySQL set ups.

Because I have no other data for testing than mine, I can't confirm that the results will produce the same results. However, I believe from the logic of the queries, this should work as expected.

If you have some testing data, I can eventually test it against it.

**Comment by bjendres** [comment]
Ok, I'll test next week in a bigger setup, and see if it works/performs well. Thanks.

**Comment by tttp** [comment]
hey @bjendres how did it go?

I'm doing some QA on wemove install... more news and hopefully greenlight from my side soon ;)

**Comment by tttp** [comment]
Been running with it smoothly for 2 months, no problem to report ;)

Let's merge? @scardinius is on my back to switch our branch to a stable one ;P

**Comment by bjendres** [comment]
@tttp fine... :)

**Comment by bjendres** [comment]
It's now in ``0.7-alpha12``. If everything works well, I'll create a beta

**Pull request merged**
