### PR TITLE
fix #346 | wrong parameter name for option group id

### LINKED ISSUE #346: Extension crashes if another option value named "import" exists
This API call returns not only the option value for the desired banking plugin type but also other option values with the name "import".
https://github.com/Project60/org.project60.banking/blob/ea20fd3a5cd5df44f7acf0754039ee97c5aef569/extension/CRM/Banking/BAO/PluginInstance.php#L54-L57
The parameter `group_id` does not exists and is ignored so the call returns all option values that match the name.
```php
array (
  'is_error' => 0,
  'version' => 3,
  'count' => 2,
  'values' => 
  array (
    1049 => 
    array (
      'id' => '1049',
      'option_group_id' => '62',
      'label' => 'Some other option value with the same name',
      'value' => '4',
      'name' => 'import',
      'filter' => '0',
      'is_default' => '0',
      'weight' => '4',
      'is_optgroup' => '0',
      'is_reserved' => '0',
      'is_active' => '1',
    ),
    1040 => 
    array (
      'id' => '1040',
      'option_group_id' => '123',
      'label' => 'Import plugin',
      'value' => '1',
      'name' => 'import',
      'filter' => '0',
      'is_default' => '0',
      'weight' => '10',
      'is_optgroup' => '0',
      'is_reserved' => '0',
      'is_active' => '1',
    ),
  ),
)
```
Because the result array contains more than one value, the following api call `BankingPluginInstance.get` cannot populate the `'plugin_type_id'` parameter with an id and therefore returns all banking plugins – not only the importers.
https://github.com/Project60/org.project60.banking/blob/ea20fd3a5cd5df44f7acf0754039ee97c5aef569/extension/CRM/Banking/BAO/PluginInstance.php#L59-L62

This behavior leads to an error when opening the import page. There, the plugin types get instantiated and called on `$class::does_import_files()`. Because this method does not exists in plugin classes which are not importers, the extension crashes.
https://github.com/Project60/org.project60.banking/blob/ea20fd3a5cd5df44f7acf0754039ee97c5aef569/extension/CRM/Banking/Page/Import.php#L99-L100
Screenshot 2021-09-21 at 18-01-39 Error CiviCRM Sandbox on Drupal

Many thanks to @sebalis and @detsieber who found and solved this problem together with me.

PR is coming! 😉

### PR DESCRIPTION
**Pull request by MarcMichalsky**
fix #346

Thanks to @sebalis and @Detsieber for working this out with me! 💪

It looks like the entire call to `OptionGroup.get` for receiving the option group id is unnecessary, so we removed that.
https://github.com/Project60/org.project60.banking/blob/ea20fd3a5cd5df44f7acf0754039ee97c5aef569/extension/CRM/Banking/BAO/PluginInstance.php#L50-L52

We changed the `OptionValue.get` call to an `OptionValue.getsingle` call to make sure it can only return one value. Also we renamed the `group_id` parameter to `option_group_id` and passed the hardcoded string for the plugin classes.
```php
// find the correct plugin type
$import_plugin_type = civicrm_api3('OptionValue', 'getsingle', array(
    'name'     => $type_name,
    'option_group_id' => 'civicrm_banking.plugin_classes'));
```

### CODE REVIEW

**Comment by MarcMichalsky** [comment]
> Since `getsingle` throws an exception on failure (other than `get`), this might introduce different behavior. Let's keep `get` although the ID is only present when there's only one result.

Hi @jensschuppe,
keeping the `get` call could still lead to the same error as described in #346. If there is more than one result, the result array will not contain the ID referenced in this line:
https://github.com/Project60/org.project60.banking/blob/4312dfffdb000c3139eb1df7c948056042e05d65/extension/CRM/Banking/BAO/PluginInstance.php#L57
The call to `OptionValue` then returns all option values with that name, which crashes the import page. 

Of course, if there is more than one result, the `getsingle` call will also produce an error. But maybe the error message is easier to interpret then.

**Comment by MarcMichalsky** [comment]
Okay, I should read your comments more carefully. You just wrote that:
> Let's keep get although the ID is only present when there's only one result.

Your decision. ☺️

**Comment by jensschuppe** [comment]
You are, of course, correct with all that, but @bjendres didn't want an exception being thrown. I also *think* that this error is theoretical because there can't be two option values with the same name in the same option group. At least that's not desired at all.

**Comment by MarcMichalsky** [comment]
> I also think that this error is theoretical because there can't be two option values with the same name in the same option group.
Yes, that's right.

**Comment by bjendres** [comment]
thanks @MarcMichalsky

**Pull request merged**
