### PR TITLE
Make it compatible with php7

### PR DESCRIPTION
**Pull request by DanielvV**
Replace deprecated (php5) / removed (php7) function split() with preg_split()

### CODE REVIEW

**Comment by DanielvV** [comment]
Don't know for sure where to use explode() vs preg_split()

**Comment by DanielvV** [comment]
Found out that preg_split uses preg and split uses ereg. Using explode() instead.

**Comment by DanielvV** [comment]
Fixes #170

**Comment by systopia** [comment]
Thanks @DanielvV

**Pull request merged**
