### PR TITLE
Skip BOM in CSV importer, e.g. for Paypal

### PR DESCRIPTION
**Pull request by being-peace**
See https://github.com/Project60/org.project60.banking/issues/300
I have not added the BOM-Skipping in the sentinel test, perhaps someone wants to test for the BOM.

### CODE REVIEW

**Comment by bjendres** [comment]
The problem with this PR is, that it would break existing solutions, where the BOM is considered part of the first column (see [HERE](https://github.com/Project60/org.project60.banking/blob/638f71fbe3b39eddbd920b8ccf9bd5428dd52189/configuration_database/Importer/CSV/StarMoney%20(with%20BOM).civibanking)). 

Frankly, I like your solution better, but there has to be a way to be backwards compatible...

**Comment by being-peace** [comment]
The existing solution is really strange: "from":"\ufeff\"Kontonummer\"" ("The quotes are a side effect of the BOM").

One could try to work around the broken configuration, but wouldn't it be more appropriate to issue a warning if a "from" field starts with \ufeff: "Your configuration contains \ufeff (BOM). This is now dealt correctly during import. Possibly correct your configuration, see [some link into the documentation]."

**Comment by bjendres** [comment]
I agree, that would make sense. Maybe that check should be done during the upgrade process, as well as when running an update. Would you be able to extend your PR?

btw: I think the _best_ solution would be for ``fgetcsv`` to support BOMs, but that's probably not happening...

**Comment by being-peace** [comment]
Unfortunately, as I have only a wordpress installation to test and the error reporting from inside CSV.php seemed not to work, I have no chance to test that. For messages during the upgrade process, I don't even know, where to look at and copy'n'paste from. :-( 

If one warns about "from" with BOM, then the BOM should also be skipped in the sentinel test and sentinels with "BOM" should be warned as well.

Do you have a chance to add the change?

**Comment by jensschuppe** [comment]
For a clean solution, there should be a configuration option in the CSV importer plugin for whether to strip the BOM or not.

**Comment by bjendres** [comment]
@being-peace I merged your PR into branch ``issue/330``, and added a switch to turn on your behaviour. All you would have to do, is to add ``"strip_bom": true``to you importer configuration.

Could you confirm that this works for you? Then I'll merge it into master...

Thanks for you contribution!

**Comment by bjendres** [comment]
I agree with you that it should work out of the box, but at the same time an update shouldn't break existing setups. An I know that in this case there are importer configurations that include the BOM in the column name of the first column, and these would stop working. 

Or am I missing something here?

**Pull request merged**
