### PR TITLE
Adds 'reset status' functionality. Implements #383

### PR DESCRIPTION
**Pull request by VangelisP**
This small addition implements a new functionality that will reset the status of the transaction from 'Processed' to 'New'. it will also remove the stored suggestions for that transaction.

This is being delivered into 2 parts:

* On the `api/v3/BankingTransaction.php` we add a new function called `civicrm_api3_banking_transaction_reset`. It accepts the transaction ID as the one and only parameter.
* On the `/templates/CRM/Banking/Page/Review.tpl` we add a new button on the analysed and ignored' transactions, along with an ajax call to the new API command mentioned above.

Screenshots:

image

image

### CODE REVIEW

**Comment by bjendres** [comment]
Great stuff! 

Does it work in both UI modes (traditional and simplified)?

**Comment by bjendres** [comment]
also... maybe we should add a configuration option to be able to turn this off, I could see that potentially causing a lot of havoc - e.g. when the reconciled transactions have been exported to accounting, and then somebody resets some of them.

**Comment by bjendres** [comment]
Does this exclusively work on ``ignored`` transactions?

**Comment by VangelisP** [comment]
Right now, yes, it works exclusively for ignored transactions. Do you think it would be better to expand this to all of them ?

I can also provide a checkbox configuration somewhere to allow to turn off this feature or not.

Lastly, let me check because I worked on the traditional UI and not the simplified one

**Comment by bjendres** [comment]
> Right now, yes, it works exclusively for ignored transactions. Do you think it would be better to expand this to all of them ?

I don't think that would be a good idea. Resetting the 'ignored' ones is already kind-of dodgy, but still waaay better then resetting otherwise processed transactions without being able to undo the changes that happened in the process (e.g. created contribution, extended membership, etc)


> I can also provide a checkbox configuration somewhere to allow to turn off this feature or not.

I think that would be great, see [HERE](https://github.com/Project60/org.project60.banking/blob/master/CRM/Admin/Form/Setting/BankingSettings.php)


> Lastly, let me check because I worked on the traditional UI and not the simplified one

If it doesn't, that's also fine - just good to know. But then maybe add a note in with the configuration option (see first item of this post).

**Comment by VangelisP** [comment]
I agree as well, resetting the status on normal transactions will cause a chaos in Production environments (good for testing but bad for live).

>I think that would be great, see [HERE](https://github.com/Project60/org.project60.banking/blob/master/CRM/Admin/Form/Setting/BankingSettings.php)

No problem! I will add that option

>If it doesn't, that's also fine - just good to know. But then maybe add a note in with the configuration option (see first item of this post).

Sure thing! :wink:

**Comment by VangelisP** [comment]
Right, so this last commit does the following:

* Adds a new checkbox in the form configuration:
* If the checkbox is enabled, we render the button of the 'Reset status' only on **ignored** transactions on **both** interfaces (simplified/traditional)

image

**Comment by Detsieber** [comment]
Sorry for my delayed comment (due to vacation).

-->> this is really great work and a significant improvement for Civibanking!

**Comment by bjendres** [comment]
Remark: this is not in ``master`` yet

**Comment by MarcMichalsky** [comment]
I would like to ask what the status is here?
In the list, this PR seems to be merged, but it was only merged into an issue branch. Will it be merged into the master branch?

**Comment by gngn23** [comment]
I'd like to join @MarcMichalsky in his question about including this in a recent release.
I could provide a PR against the 1.3.x branch if that helps.

I was able to apply the diff to release **1.2.0** by hand using `patch -p1 < DIFF-FILE`.
```
patching file CRM/Admin/Form/Setting/BankingSettings.php
Hunk #3 succeeded at 215 with fuzz 2.
patching file CRM/Banking/Page/Review.php
patching file api/v3/BankingTransaction.php
patching file templates/CRM/Admin/Form/Setting/BankingSettings.tpl
patching file templates/CRM/Banking/Page/Review.tpl
```

Un-ignore (aka "Reset status") worked for me with this.

---
Patching release **1.3.2** would be a tiny bit more complicated (because `CRM/Admin/Form/Setting/BankingSettings.php` changed some more), but I think this is quite simple to fix.
Since I am going to evaluate 1.3.2 anyway, I will also test the un-ignore-transaction feature.

---
I did not succeed to apply the diff to **1.4.0-beta1**.

**Comment by jensschuppe** [comment]
I created #501 as a rebased version of this PR, so that it doesn't go unnoticed anymore.

**Pull request merged**
