### PR TITLE
Documentation updates

### LINKED ISSUE #401: Documentation updates
First of all - thank you for your great work! This extension is of great importance for a lot of institutions. 
Based on feedback from different implementations of CiviBanking we have extended the documentation on the migrations, analyser and matcher sections. Also the introduction and concept sections of the documentation have been re-organised and extended, so that important information is available inside the general information, either directly as text or interlinked. 
We have done our best to accumulate helpful tips for implementers, as well as short best-practices for the organizational set-up (bank accounts, organizing your migration sources, etc.) 
As the changes affect multiple documents, we have allowed ourselves to prepare them directly for a pull request, which will follow shortly.
 
This issue and the related PR were created during the CiviSprint Leipzig 2023.

### PR DESCRIPTION
**Pull request by RositzaDikova**
Fix #401 
Updated the documentation sections for import, analysers and matchers, provided more information for implementers based on  compact examples.

### CODE REVIEW

**Comment by MarcMichalsky** [comment]
I would like to make a few changes to the content and visuals. I will submit a PR on your fork.

**Comment by RositzaDikova** [comment]
@MarcMichalsky  Thank you for this! I have converted the PR to draft for now - I hope this is OK.

**Comment by MarcMichalsky** [comment]
I created a [PR](https://github.com/RositzaDikova/org.project60.banking/pull/1)  on your branch, @RositzaDikova!

**Comment by RositzaDikova** [comment]
This is a follow up on the documentation updates/improvements, started off during the CiviSprint in Leipzig 2023 and now ready for review. 

@jensschuppe  Dear Jens, you seem to be the person most recently involved in documentation updates issues and PRs, so I kindly ask for your attention on the pull request. 

Big thanks goes to @MarcMichalsky who has improved greatly the analyzer and matchers section, and of course to all involved in the updates during the sprint!

**Comment by jensschuppe** [comment]
I'm afraid I won't get to thoroughly reviewing this anytime soon, so I'd suggest we just merge it (as it's docs only) and rely on your extensive work (Thanks!), and, more importantly, people testing their configuration, even when strictly following the docs.

I guess you "prosaized" the actual code for the individual plugins, so this should be accurate.

One thing, `mkdocs serve` has this warning:
```
INFO    -  The following pages exist in the docs directory, but are not included in the "nav" configuration:
             - reference.md
             - configuration/plugins/importer-actions.md
```
@RositzaDikova or @MarcMichalsky could you address this?

@bjendres anything more to add before merging?

**Comment by RositzaDikova** [comment]
@jensschuppe  Sorry for not replying earlier on this! 

-  _"prosaized" the actual code for the individual plugins_ - Yes indeed!
- Both pages mentioned are interlinked from different sections of concept.md and the index. I don´t see a problem, if they remain out of the navigation tree (remain linked/referenced only in context).

**Comment by jensschuppe** [comment]
I personally really like the concept of having every page in the navigation tree somewhere for quick access and for seeing where in the tree I am when viewing the page, so I'd vote for adding it somewhere. Also, I think the docs publisher on civicrm.org will complain about such issues, but I'm not sure …

Anyway, the link to `importer-actions.md` is a link to the file on GitHub, I guess that should be a relative link so that the file will be opened within the MKDocs book.

**Comment by jensschuppe** [comment]
Thanks a lot @RositzaDikova and @MarcMichalsky for your efforts in improving the *CiviBanking* docs!

In all its glory: https://docs.civicrm.org/banking

**Pull request merged**
