### PR TITLE
improve CsvImporter 'amount' to filter thousand separators

### PR DESCRIPTION
**Pull request by sleidig**
We were facing problems with some bank statement imports that included amounts with the German formatting including thousand separators like `10.000,00` which resulted in an imported amount of "10.00" instead of "10000.00".
As I failed to write a RegexAnalyser to fix the values I patched the Importer and propose this PR.

### CODE REVIEW

**Comment by bjendres** [comment]
@sleidig: Good idea. However, I suggest creating a separate action (e.g. ``amountparse``), so we can be sure we don't break the existing configurations for anyone... What do you think?

**Comment by sleidig** [comment]
That's a fair point. We all hate those hidden breaking changes ;-)
Although you could also argue that this PR is actually a bugfix - without it I am getting wrong amounts parsed.

changed it according to your suggestion

**Comment by bjendres** [comment]
great stuff, thanks @sleidig !

**Comment by bjendres** [comment]
Released with ``0.7``

**Pull request merged**
