### PR TITLE
Update importer and add as a second option for GLS

### PR DESCRIPTION
**Pull request by wintermoor**
GLS changed csv format. This importer is for CSV dated in June 2021.

### CODE REVIEW

**Comment by jensschuppe** [comment]
Any reason why deleting the old file and naming the new one differently?

**Comment by bjendres** [comment]
@wintermoor Is this PR really just about renaming the file? Or if this is another file, why delete the old one? Could you explain?

**Comment by wintermoor** [comment]
Hej @bjendres , this is a new file. GLS bank changed their exports, therefore we won't need the old one anymore. Maybe I didn't make this clear on Github.

**Comment by bjendres** [comment]
Shouldn't we then leave the old one and change the name to "outdated" or something? Just to be clear about it, and not take it away from other people (maybe with other banks) who it's still working for. Would you mind adjusting the PR?

**Comment by wintermoor** [comment]
Dear @bjendres sorry, I don't know how to undelete a file in Github. 

More important: This PR is outdated, because GLS (and Volks/Raiffeisenbanken) changed their CSV-export files in May 2022 again. These changes are already included in commit c7cc14f80e6c278d56f2fcef5ee80958395d87d3 on Sept 8th 2022. 

I'll close this PR right now. Best wishes!

**Pull request closed without merging**
