### PR TITLE
split() is depricated

### PR DESCRIPTION
**Pull request by danielvv**

### CODE REVIEW

**Comment by DanielvV** [comment]
Fixes #187

**Comment by DanielvV** [comment]
split is with regular expressions
explode not

http://php.net/manual/en/function.split.php
http://php.net/manual/en/function.explode.php

**Comment by systopia** [comment]
Thanks, @danielvv. I went a slightly different way with this one: https://github.com/Project60/org.project60.banking/commit/d33a658cb88543a714789e6b41c67568a376695b

Or do you see any problem with this?

**Comment by danielvv** [comment]
That works to. I don't see the added value though...

**Pull request closed without merging**
